### ISSUE TITLE
execute node node_modules/@hydro-sdk/hydro-sdk/dist/compiler failed

### ISSUE THREAD

**Issue by lyxia** [hydro-sdk/hydro_demo#206]
node node_modules/@hydro-sdk/hydro-sdk/dist/compiler -t ota/hello-world.ts -m hello-world -d assets -p debug
Build d9a053b259311d6139ba1bac901853eecc21ffe77544d4222082ddbf70bb3550
Compiling  [----------------------------------------] 1/202 dart/collection/list.ts(node:40938) UnhandledPromiseRejectionWarning: TypeError: utils_1.castArray(...).flatMap isn
    at TransformationContext.transformStatements (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript-to-lua/dist/transformation/context/context.js:71:40)
    at Object.exports.transformSourceFileNode [as transform] (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript-to-lua/dist/transformation/visitors/source)
    at TransformationContext.transformNode (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript-to-lua/dist/transformation/context/context.js:45:62)
    at Object.transformSourceFile (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript-to-lua/dist/transformation/index.js:29:30)
    at processSourceFile (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript-to-lua/dist/transpilation/transpile.js:52:96)
    at sourceFile (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript-to-lua/dist/transpilation/transformers.js:22:9)
    at transformSourceFileOrBundle (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript/lib/typescript.js:74631:57)
    at transformation (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript/lib/typescript.js:92009:24)
    at transformRoot (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript/lib/typescript.js:92030:82)
    at Object.map (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript/lib/typescript.js:551:29)
(node:40938) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by )
(node:40938) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js proc.
^C
liuyunxiadeMacBook-Pro:hydro_demo liuyunxia$ node node_modules/@hydro-sdk/hydro-sdk/dist/compiler -t ota/hello-world.ts -m hello-world -d assets -p debug
Build d9a053b259311d6139ba1bac901853eecc21ffe77544d4222082ddbf70bb3550
Compiling  [----------------------------------------] 1/202 dart/collection/list.ts(node:41142) UnhandledPromiseRejectionWarning: TypeError: utils_1.castArray(...).flatMap isn
    at TransformationContext.transformStatements (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript-to-lua/dist/transformation/context/context.js:71:40)
    at Object.exports.transformSourceFileNode [as transform] (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript-to-lua/dist/transformation/visitors/source)
    at TransformationContext.transformNode (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript-to-lua/dist/transformation/context/context.js:45:62)
    at Object.transformSourceFile (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript-to-lua/dist/transformation/index.js:29:30)
    at processSourceFile (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript-to-lua/dist/transpilation/transpile.js:52:96)
    at sourceFile (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript-to-lua/dist/transpilation/transformers.js:22:9)
    at transformSourceFileOrBundle (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript/lib/typescript.js:74631:57)
    at transformation (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript/lib/typescript.js:92009:24)
    at transformRoot (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript/lib/typescript.js:92030:82)
    at Object.map (/Users/liuyunxia/Documents/flutter/hydro_demo/node_modules/typescript/lib/typescript.js:551:29)
(node:41142) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by )
(node:41142) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js proc.

**Comment by lyxia** [comment]
Related to https://github.com/hydro-sdk/hydro-sdk/issues/322。
